language: node_js
node_js:
  - "4.1"
  - "4.0"

sudo: required
dist: trusty

service:
  - docker

script: 
  - docker build -t gh-review .
  - bin/gh-review -h
  - bin/gh-review PredictTheSky
  - docker run gh-review -h
  - docker run -i gh-review PredictTheSky
